apiVersion: v1
kind: Service
metadata:
  name: hello-eks-custom
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-eks-custom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-eks-custom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-eks-custom
  template:
    metadata:
      labels:
        app: hello-eks-custom
    spec:
      containers:
      - name: hello-eks
        image: marceloboeira/hello-eks:1.0
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: I just deployed this on eks!
